well_commerce_tax:
    configuration:
        tax:
            orm:
                factory: WellCommerce\Bundle\TaxBundle\Factory\TaxFactory
                repository: WellCommerce\Bundle\TaxBundle\Repository\TaxRepository
                mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/Tax.orm.yml"
                entity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            api:
                exposed: true
                dataset: tax.dataset.admin
                manager: tax.manager
        tax_translation:
            orm:
                manager: false
                mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/TaxTranslation.orm.yml"
                entity: WellCommerce\Bundle\TaxBundle\Entity\TaxTranslation

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\TaxBundle\Entity\TaxTranslation:
                properties:
                    - name
