admin.tax.index:
    path: /admin/configuration/tax/index
    defaults:
        _controller: 'tax.controller.admin:indexAction'
    options:
        require_permission: 'true'
        require_admin_permission: tax.index
admin.tax.grid:
    path: /admin/configuration/tax/grid
    defaults:
        _controller: 'tax.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: tax.index
admin.tax.add:
    path: /admin/configuration/tax/add
    defaults:
        _controller: 'tax.controller.admin:addAction'
    options:
        require_admin_permission: tax.add
admin.tax.edit:
    path: '/admin/configuration/tax/edit/{id}'
    defaults:
        _controller: 'tax.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: tax.edit
admin.tax.delete:
    path: '/admin/configuration/tax/delete/{id}'
    defaults:
        _controller: 'tax.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: tax.delete
