WellCommerce\Bundle\TaxBundle\Entity\Tax:
    fields:
        id:
            groups:
                - default
                - tax
        value:
            groups:
                - default
                - tax
    associations:
        translations:
            groups:
                - tax
