# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\TaxBundle\Entity\TaxInterface: WellCommerce\Bundle\TaxBundle\Entity\Tax

well_commerce_doctrine:
    configuration:
        tax:
            factory: WellCommerce\Bundle\TaxBundle\Factory\TaxFactory
            repository: WellCommerce\Bundle\TaxBundle\Repository\TaxRepository
            mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/Tax.orm.yml"
            entity: WellCommerce\Bundle\TaxBundle\Entity\Tax
        tax_translation:
            manager: false
            mapping: "@WellCommerceTaxBundle/Resources/config/doctrine/TaxTranslation.orm.yml"
            entity: WellCommerce\Bundle\TaxBundle\Entity\TaxTranslation
