# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.tax.index:
    path: /index
    defaults:
        _controller: 'tax.controller.admin:indexAction'
    options:
        require_permission: 'true'
        require_admin_permission: tax.index

admin.tax.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'tax.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: tax.index

admin.tax.add:
    path: /add
    defaults:
        _controller: 'tax.controller.admin:addAction'
    options:
        require_admin_permission: tax.add

admin.tax.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'tax.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: tax.edit

admin.tax.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'tax.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: tax.delete

admin.tax.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'tax.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: tax.delete
